{
    "name": "Account Statement Report",
    "version": "14.0.0.1.0",
    "category": "Product",
    "summary": "Account Statement Report",
    "author": "Elaraby",
    "website": "https://www.ibs-na.com",
    "license": "AGPL-3",
    "depends": ['base','stock', 'report_xlsx','account', 'partner_category', 'allowed_journals', 'access_partner_id'],
    "data": [
        "security/ir.model.access.csv",
        "wizard/account_statement_wizard_views.xml",
        "wizard/invoice_details_wizard_views.xml",
        "wizard/bt_cash_wizard_views.xml",
        "reports/account_report_template.xml",
        "reports/invoice_details_template.xml",
        "reports/bt_cash_template.xml",
        "reports/action_reports.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}