{
    "name": "Product Report",
    "version": "14.0.0.1.0",
    "category": "Product",
    "summary": "Product Profitability Report",
    "author": "IBS",
    "website": "https://www.ibs-na.com",
    "license": "AGPL-3",
    "depends": ['base','stock', 'report_xlsx','account', 'partner_category', 'inventory_report'],
    "data": [
        "security/ir.model.access.csv",
        "views/account_move_line2_views.xml",
        "views/sales_plan_views.xml",
        "wizard/profitability_wizard_views.xml",
        "reports/profitability_template_views.xml",
        "reports/action_reports.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}