{
    "name": "Expense Report",
    "version": "14.0.0.1.0",
    "category": "Product",
    "summary": "Expense Product Report",
    "author": "IBS",
    "website": "https://www.ibs-na.com",
    "license": "AGPL-3",
    "depends": ['base','stock', 'report_xlsx','account', 'partner_category', 'allowed_journals'],
    "data": [
        "security/ir.model.access.csv",
        # "views/account_move_line2_views.xml",
        "views/account_account_views.xml",
        "views/account_move_views.xml",
        "views/account_tax_views.xml",
        "wizard/expense_wizard_views.xml",
        "reports/expense_template_views.xml",
        "reports/action_reports.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}